<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyVersion>10.0.0.0</AssemblyVersion>
    <FileVersion>10.0.0.0</FileVersion>
    <Version>10.0.0</Version>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
</Project>